"""add parkings

Revision ID: bd3adc9c4e27
Revises: eb6b4e5f1563
Create Date: 2023-01-31 22:43:49.297238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd3adc9c4e27"
down_revision = "eb6b4e5f1563"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parking_addresses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("street", sa.String(length=100), nullable=False),
        sa.Column("zip_code", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parkings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address_id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"], ["parking_addresses.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parkings")
    op.drop_table("parking_addresses")
    # ### end Alembic commands ###
