"""add booking

Revision ID: c18e73c205d7
Revises: 8fb899421801
Create Date: 2023-02-08 21:18:30.711032

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c18e73c205d7"
down_revision = "8fb899421801"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("booker_id", sa.UUID(), nullable=False),
        sa.Column("parking_space_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["booker_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parking_space_id"], ["parking_spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    # ### end Alembic commands ###
