name: App Build
description: "Build Poetry x Python Project"

inputs:
  py-version:
    description: "Python version"
    required: true
    default: 3.11.0
  poetry-version:
    description: "Poetry version"
    required: true
    default: 1.3.1

runs:
  using: "composite"
  steps:
  - name: Set Up Python
    uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.py-version }}
  - name: Install Poetry
    uses: abatilo/actions-poetry@v2
    with:
      poetry-version: ${{ inputs.poetry-version }}
  - name: Install Dependencies
    shell: 'bash'
    run: poetry install
